export const SET_LOADING = 'SET_LOADING'



//--------------------------------------- AGRO RECORDS------------------------------------------------------------------
export const ADD_AGRO_RECORD = 'ADD_AGRO_RECORD'
export const SET_SELECTED_AGRO_RECORD  = 'SET_SELECTED_AGRO_RECORD '
export const SET_ALL_AGRO_RECORDS = 'SET_ALL_AGRO_RECORDS'
export const GET_ALL_AGRO_RECORDS = 'GET_ALL_AGRO_RECORDS'
export const COMPLETE_AGRO_RECORD = 'COMPLETE_AGRO_RECORD'

export const GET_ALL_LANDSCAPING_RECORDS = 'GET_ALL_LANDSCAPING_RECORDS'
export const SET_ALL_LANDSCAPING_RECORDS = 'SET_ALL_LANDSCAPING_RECORDS'

export const GET_ALL_PEST_CONTROL_VEG_RECORDS= 'GET_ALL_PEST_CONTROL_VEG_RECORDS'
export const GET_ALL_HOUSEHOLD_TERMITES_CONTROL_RECORDS = 'GET_ALL_HOUSEHOLD_TERMITES_CONTROL_RECORDS'
export const GET_ALL_AGRIC_FIELD_TERMITE_CONTROL_RECORDS = 'GET_ALL_AGRIC_FIELD_TERMITE_CONTROL_RECORDS'
export const GET_ALL_GRAIN_PROTECTION_RECORDS = 'GET_ALL_GRAIN_PROTECTION_RECORDS'
export const GET_ALL_WEED_CONTROL_RECORDS = 'GET_ALL_WEED_CONTROL_RECORDS'
export const GET_ALL_PEST_CONTROL_FIELD_RECORDS = 'GET_ALL_PEST_CONTROL_FIELD_RECORDS'
export const GET_ALL_PUBLIC_HEALTH_PEST_CONTROL_RECORDS = 'GET_ALL_PUBLIC_HEALTH_PEST_CONTROL_RECORDS'
export const GET_ALL_VEG_ENTERPRISE_BUDGET_RECORDS = 'GET_ALL_VEG_ENTERPRISE_BUDGET_RECORDS'
export const GET_ALL_PEST_CONTROL_ORCHARDS_RECORDS = 'GET_ALL_PEST_CONTROL_ORCHARDS_RECORDS'
export const GET_ALL_SOIL_ANALYSIS_RECORDS = 'GET_ALL_SOIL_ANALYSIS_RECORDS'



export const SET_ALL_PEST_CONTROL_VEG_RECORDS= 'SET_ALL_PEST_CONTROL_VEG_RECORDS'
export const SET_ALL_HOUSEHOLD_TERMITES_CONTROL_RECORDS = 'SET_ALL_HOUSEHOLD_TERMITES_CONTROL_RECORDS'
export const SET_ALL_AGRIC_FIELD_TERMITE_CONTROL_RECORDS = 'SET_ALL_AGRIC_FIELD_TERMITE_CONTROL_RECORDS'
export const SET_ALL_GRAIN_PROTECTION_RECORDS = 'SET_ALL_GRAIN_PROTECTION_RECORDS'
export const SET_ALL_WEED_CONTROL_RECORDS = 'SET_ALL_WEED_CONTROL_RECORDS'
export const SET_ALL_PEST_CONTROL_FIELD_RECORDS = 'SET_ALL_PEST_CONTROL_FIELD_RECORDS'
export const SET_ALL_PUBLIC_HEALTH_PEST_CONTROL_RECORDS = 'SET_ALL_PUBLIC_HEALTH_PEST_CONTROL_RECORDS'
export const SET_ALL_VEG_ENTERPRISE_BUDGET_RECORDS = 'SET_ALL_VEG_ENTERPRISE_BUDGET_RECORDS'
export const SET_ALL_PEST_CONTROL_ORCHARDS_RECORDS = 'SET_ALL_PEST_CONTROL_ORCHARDS_RECORDS'
export const SET_ALL_SOIL_ANALYSIS_RECORDS = 'SET_ALL_SOIL_ANALYSIS_RECORDS'


//----------------------------------------------------------------------------------------------------------------------


//--------------------------------------- VET RECORDS------------------------------------------------------------------
export const ADD_VET_RECORD = 'ADD_VET_RECORD'
export const SET_SELECTED_VET_RECORD  = 'SET_SELECTED_VET_RECORD '
export const SET_ALL_VET_RECORDS = 'SET_ALL_VET_RECORDS'
export const GET_ALL_VET_RECORDS = 'GET_ALL_VET_RECORDS'
export const COMPLETE_VET_RECORD = 'COMPLETE_VET_RECORD'

//----------------------------------------------------------------------------------------------------------------------



