export const SET_LOADING = 'SET_LOADING'

export const GET_ALL_USERS = 'GET_ALL_USERS'

//--------------------------------------- AGRO RECORDS------------------------------------------------------------------
export const ADD_AGRO_RECORD = 'ADD_AGRO_RECORD'
export const SET_SELECTED_AGRO_RECORD  = 'SET_SELECTED_AGRO_RECORD '
export const SET_ALL_AGRO_RECORDS = 'SET_ALL_AGRO_RECORDS'
export const GET_ALL_AGRO_RECORDS = 'GET_ALL_AGRO_RECORDS'
export const COMPLETE_AGRO_RECORD = 'COMPLETE_AGRO_RECORD'
export const GET_FILTERED_START_TIME = 'GET_FILTERED_START_TIME'
export const GET_FILTERED_END_TIME = 'GET_FILTERED_END_TIME'
export const GET_ALL_LANDSCAPING_RECORDS = 'GET_ALL_LANDSCAPING_RECORDS'
export const SET_ALL_LANDSCAPING_RECORDS = 'SET_ALL_LANDSCAPING_RECORDS'

export const GET_ALL_PEST_CONTROL_VEG_RECORDS= 'GET_ALL_PEST_CONTROL_VEG_RECORDS'
export const GET_ALL_HOUSEHOLD_TERMITES_CONTROL_RECORDS = 'GET_ALL_HOUSEHOLD_TERMITES_CONTROL_RECORDS'
export const GET_ALL_AGRIC_FIELD_TERMITE_CONTROL_RECORDS = 'GET_ALL_AGRIC_FIELD_TERMITE_CONTROL_RECORDS'
export const GET_ALL_GRAIN_PROTECTION_RECORDS = 'GET_ALL_GRAIN_PROTECTION_RECORDS'
export const GET_ALL_WEED_CONTROL_RECORDS = 'GET_ALL_WEED_CONTROL_RECORDS'
export const GET_ALL_PEST_CONTROL_FIELD_RECORDS = 'GET_ALL_PEST_CONTROL_FIELD_RECORDS'
export const GET_ALL_PUBLIC_HEALTH_PEST_CONTROL_RECORDS = 'GET_ALL_PUBLIC_HEALTH_PEST_CONTROL_RECORDS'
export const GET_ALL_VEG_ENTERPRISE_BUDGET_RECORDS = 'GET_ALL_VEG_ENTERPRISE_BUDGET_RECORDS'
export const GET_ALL_PEST_CONTROL_ORCHARDS_RECORDS = 'GET_ALL_PEST_CONTROL_ORCHARDS_RECORDS'
export const GET_ALL_SOIL_ANALYSIS_RECORDS = 'GET_ALL_SOIL_ANALYSIS_RECORDS'



export const SET_ALL_PEST_CONTROL_VEG_RECORDS= 'SET_ALL_PEST_CONTROL_VEG_RECORDS'
export const SET_ALL_HOUSEHOLD_TERMITES_CONTROL_RECORDS = 'SET_ALL_HOUSEHOLD_TERMITES_CONTROL_RECORDS'
export const SET_ALL_AGRIC_FIELD_TERMITE_CONTROL_RECORDS = 'SET_ALL_AGRIC_FIELD_TERMITE_CONTROL_RECORDS'
export const SET_ALL_GRAIN_PROTECTION_RECORDS = 'SET_ALL_GRAIN_PROTECTION_RECORDS'
export const SET_ALL_WEED_CONTROL_RECORDS = 'SET_ALL_WEED_CONTROL_RECORDS'
export const SET_ALL_PEST_CONTROL_FIELD_RECORDS = 'SET_ALL_PEST_CONTROL_FIELD_RECORDS'
export const SET_ALL_PUBLIC_HEALTH_PEST_CONTROL_RECORDS = 'SET_ALL_PUBLIC_HEALTH_PEST_CONTROL_RECORDS'
export const SET_ALL_VEG_ENTERPRISE_BUDGET_RECORDS = 'SET_ALL_VEG_ENTERPRISE_BUDGET_RECORDS'
export const SET_ALL_PEST_CONTROL_ORCHARDS_RECORDS = 'SET_ALL_PEST_CONTROL_ORCHARDS_RECORDS'
export const SET_ALL_SOIL_ANALYSIS_RECORDS = 'SET_ALL_SOIL_ANALYSIS_RECORDS'


//----------------------------------------------------------------------------------------------------------------------

//--------------------------------------- NUTRITION RECORDS------------------------------------------------------------------
export const ADD_NUTRITION_RECORD = 'ADD_NUTRITION_RECORD'
export const SET_SELECTED_NUTRITION_RECORD = 'SET_SELECTED_NUTRITION_RECORD '
export const SET_ALL_NUTRITION_RECORDS = 'SET_ALL_NUTRITION_RECORDS'
export const GET_ALL_NUTRITION_RECORDS = 'GET_ALL_NUTRITION_RECORDS'

export const GET_FILTERED_NUTRITION_START_TIME = 'GET_FILTERED_NUTRITION_START_TIME'
export const GET_FILTERED_NUTRITION_END_TIME = 'GET_FILTERED_NUTRITION_END_TIME'


export const GET_ALL_NUTRITION_CATTLE_RECORDS = 'GET_ALL_NUTRITION_CATTLE_RECORDS'
export const GET_ALL_NUTRITION_GOATS_RECORDS = 'GET_ALL_NUTRITION_GOATS_RECORDS'
export const GET_ALL_NUTRITION_SHEEP_RECORDS = 'GET_ALL_NUTRITION_SHEEP__RECORDS'
export const GET_ALL_NUTRITION_PIGS_RECORDS = 'GET_ALL_NUTRITION_PIGS_RECORDS'
export const GET_ALL_NUTRITION_POULTRY_RECORDS = 'GET_ALL_NUTRITION_POULTRY_RECORDS'
export const GET_ALL_NUTRITION_DOGS_AND_CATS_RECORDS = 'GET_ALL_NUTRITION_DOGS_AND_CATS_RECORDS'
export const GET_ALL_NUTRITION_RABBITS_RECORDS = 'GET_ALL_NUTRITION_RABBITS_RECORDS'
export const GET_ALL_NUTRITION_WILDLIFE_OR_EXOTICS_RECORDS = 'GET_ALL_NUTRITION_WILDLIFE_OR_EXOTICS_RECORDS'
export const GET_ALL_NUTRITION_HORSES_RECORDS = 'GET_ALL_HORSES_RECORDS'

//================================END OF SECTION=========================================//




//--------------------------------------- VET RECORDS------------------------------------------------------------------
export const ADD_VET_RECORD = 'ADD_VET_RECORD'
export const SET_SELECTED_VET_RECORD  = 'SET_SELECTED_VET_RECORD '
export const SET_ALL_VET_RECORDS = 'SET_ALL_VET_RECORDS'
export const GET_ALL_VET_RECORDS = 'GET_ALL_VET_RECORDS'
export const COMPLETE_VET_RECORD = 'COMPLETE_VET_RECORD'
export const GET_FILTERED_VET_START_TIME = 'GET_FILTERED_VET_START_TIME'
export const GET_FILTERED_VET_END_TIME = 'GET_FILTERED_VET_END_TIME'


export const GET_ALL_CATTLE_RECORDS = 'GET_ALL_CATTLE_RECORDS'
export const GET_ALL_GOATS_RECORDS = 'GET_ALL_GOATS_RECORDS'
export const GET_ALL_SHEEP_RECORDS = 'GET_ALL_SHEEP__RECORDS'
export const GET_ALL_PIGS_RECORDS = 'GET_ALL_PIGS_RECORDS'
export const GET_ALL_POULTRY_RECORDS = 'GET_ALL_POULTRY_RECORDS'
export const GET_ALL_DOGS_AND_CATS_RECORDS = 'GET_ALL_DOGS_AND_CATS_RECORDS'
export const GET_ALL_RABBITS_RECORDS = 'GET_ALL_RABBITS_RECORDS'
export const GET_ALL_WILDLIFE_OR_EXOTICS_RECORDS = 'GET_ALL_WILDLIFE_OR_EXOTICS_RECORDS'
export const GET_ALL_HORSES_RECORDS = 'GET_ALL_HORSES_RECORDS'


export const SET_ALL_CATTLE_RECORDS = 'SET_ALL_CATTLE_RECORDS'
export const SET_ALL_GOATS_RECORDS = 'SET_ALL_GOATS_RECORDS'
export const SET_ALL_SHEEP_RECORDS = 'SET_ALL_SHEEP__RECORDS'
export const SET_ALL_PIGS_RECORDS = 'SET_ALL_PIGS_RECORDS'
export const SET_ALL_POULTRY_RECORDS = 'SET_ALL_POULTRY_RECORDS'
export const SET_ALL_DOGS_AND_CATS_RECORDS = 'SET_ALL_DOGS_AND_CATS_RECORDS'
export const SET_ALL_RABBITS_RECORDS = 'SET_ALL_RABBITS_RECORDS'
export const SET_ALL_WILDLIFE_OR_EXOTICS_RECORDS = 'SET_ALL_WILDLIFE_OR_EXOTICS_RECORDS'
export const SET_ALL_HORSES_RECORDS = 'SET_ALL_HORSES_RECORDS'




//----------------------------------------VET POST MORTEMS-------------------------------/
export const  ADD_NEW_POST_MORTEM_RECORD = ' ADD_NEW_POST_MORTEM_RECORD'
export const GET_ALL_POST_MORTEM_RECORDS = 'GET_ALL_POST_MORTEM_RECORDS'
export const SET_ALL_POST_MORTEM_RECORDS = 'SET_ALL_POST_MORTEM_RECORDS'



//--------------------------------VILLAGE CHICKEN DISEASES--------------------------//

export const GET_FILTERED_VET_PM_START_TIME = 'GET_FILTERED_VET_PM_START_TIME'
export const GET_FILTERED_VET_PM_END_TIME = 'GET_FILTERED_VET_PM_END_TIME'


export const GET_ALL_IL_RECORDS = 'GET_ALL_IL_RECORDS'
export const GET_ALL_NEWCASTLE_RECORDS = 'GET_ALL_NEWCASTLE_RECORDS'
export const GET_ALL_GUMBORO_RECORDS = 'GET_ALL_GUMBORO_RECORDS'
export const GET_ALL_COCCIDIOSIS_RECORDS = 'GET_ALL_COCCIDIOSIS_RECORDS'
export const GET_ALL_FOWL_POX_RECORDS = 'GET_ALL_FOWL_POX_RECORDS' 
export const GET_ALL_EGG_PERITONITIS_RECORDS  = 'GET_ALL_EGG_PERITONITIS_RECORDS '
export const GET_ALL_ECTOPARASITES_RECORDS = 'GET_ALL_ECTOPARASITES_RECORDS'
export const GET_ALL_HELMINTHIASIS_RECORDS = 'GET_ALL_HELMINTHIASIS_RECORDS'
export const GET_ALL_MYCOPLASMOSIS_RECORDS = 'GET_ALL_MYCOPLASMOSIS_RECORDS'
export const GET_ALL_SNAKE_BITE_RECORDS = 'GET_ALL_SNAKE_BITE_RECORDS'
export const GET_ALL_COLIBACILLOSIS_RECORDS = 'GET_ALL_COLIBACILLOSIS_RECORDS'
export const GET_ALL_CHRONIC_INFECTIOUS_BRONCHY_RECORDS = 'GET_ALL_CHRONIC_INFECTIOUS_BRONCHY_RECORDS'

//----------------------------------------------------------------------------------------------------------------------



//--------------------------------BROILER CHICKEN DISEASES--------------------------//

export const GET_FILTERED_BROILER_PM_START_TIME = 'GET_FILTERED_BROILER_PM_START_TIME'
export const GET_FILTERED_BROILER_PM_END_TIME = 'GET_FILTERED_BROILER_PM_END_TIME'



export const GET_ALL_BROILER_NEWCASTLE_RECORDS = 'GET_ALL_BROILER_NEWCASTLE_RECORDS'
export const GET_ALL_BROILER_GUMBORO_RECORDS = 'GET_ALL_BROILER_GUMBORO_RECORDS'
export const GET_ALL_BROILER_COCCIDIOSIS_RECORDS = 'GET_ALL_BROILER_COCCIDIOSIS_RECORDS'
export const GET_ALL_BROILER_COLIBACILLOSIS_RECORDS = 'GET_ALL_BROILER_COLIBACILLOSIS_RECORDS'
export const GET_ALL_BROILER_CHRONIC_RESP_DISEASE_RECORDS = 'GET_ALL_BROILER_CHRONIC_RESP_DISEASE_RECORDS'
export const GET_ALL_BROILER_HEAT_STRESS_RECORDS = 'GET_ALL_BROILER_HEAT_STRESS_RECORDS'
export const GET_ALL_BROILER_INFECTIOUS_CORYZA_RECORDS = 'GET_ALL_BROILER_INFECTIOUS_CORYZA_RECORDS'
export const GET_ALL_BROILER_ASCITES_RECORDS = 'GET_ALL_BROILER_ASCITES_RECORDS'
export const GET_ALL_BROILER_TRAUMA_RECORDS = 'GET_ALL_BROILER_TRAUMA_RECORDS'
//----------------------------------------------------------------------------------------------------------------------



//----------------------------LAYER CHICKEN DISEASES--------------------------------//
export const GET_FILTERED_LAYER_PM_START_TIME = 'GET_FILTERED_LAYER_PM_START_TIME'
export const GET_FILTERED_LAYER_PM_END_TIME = 'GET_FILTERED_LAYER_PM_END_TIME'



export const   GET_ALL_LAYER_NEWCASTLE_RECORDS = 'GET_ALL_LAYER_NEWCASTLE_RECORDS'
export const   GET_ALL_LAYER_GUMBORO_RECORDS = 'GET_ALL_LAYER_GUMBORO_RECORDS'
export const   GET_ALL_LAYER_FATTY_LIVER_HS_RECORDS = 'GET_ALL_LAYER_FATTY_LIVER_HS_RECORDS'
export const   GET_ALL_LAYER_EGG_PERITONITIS_RECORDS = 'GET_ALL_LAYER_EGG_PERITONITIS_RECORDS' 
export const   GET_ALL_LAYER_COCCIDIOSIS_RECORDS = 'GET_ALL_LAYER_COCCIDIOSIS_RECORDS'
export const   GET_ALL_LAYER_INFECTIOUS_BRONCHITIS_RECORDS = 'GET_ALL_LAYER_INFECTIOUS_BRONCHITIS_RECORDS'
export const   GET_ALL_LAYER_HELMINTHIASIS_RECORDS = 'GET_ALL_LAYER_HELMINTHIASIS_RECORDS'
export const   GET_ALL_LAYER_LARYNGOTRACHEITIS_RECORDS = 'GET_ALL_LAYER_LARYNGOTRACHEITIS_RECORDS'
export const   GET_ALL_LAYER_CALCIUM_DEFICIENCY_RECORDS = 'GET_ALL_LAYER_CALCIUM_DEFICIENCY_RECORDS'


//-------------------------------------END OF LAYER SECTION------------------------------//

//----------------------------PIG DISEASES--------------------------------//
export const GET_FILTERED_PIG_PM_START_TIME = 'GET_FILTERED_PIG_PM_START_TIME'
export const GET_FILTERED_PIG_PM_END_TIME = 'GET_FILTERED_PIG_PM_END_TIME'



export const   GET_ALL_PIG_MYCOPLASMOSIS_RECORDS = 'GET_ALL_PIG_MYCOPLASMOSIS_RECORDS'
export const   GET_ALL_PIG_PNEUMONIA_RECORDS = 'GET_ALL_PIG_PNEUMONIA_RECORDS'
export const   GET_ALL_PIG_CLOSTRIDIAL_INFECTION_RECORDS = 'GET_ALL_PIG_CLOSTRIDIAL_INFECTION_RECORDS'
export const   GET_ALL_PIG_ENTERITIS_RECORDS = 'GET_ALL_PIG_ENTERITIS_RECORDS'


//--------------------------END OF PIG SECTION-------------------------------------//


//----------------------------GOAT DISEASES--------------------------------//
export const GET_FILTERED_GOAT_PM_START_TIME = 'GET_FILTERED_GOAT_PM_START_TIME'
export const GET_FILTERED_GOAT_PM_END_TIME = 'GET_FILTERED_GOAT_PM_END_TIME'



export const   GET_ALL_GOAT_HELMINTHIASIS_RECORDS = 'GET_ALL_GOAT_HELMINTHIASIS_RECORDS'
export const   GET_ALL_GOAT_HEARTWATER_RECORDS = 'GET_ALL_GOAT_HEARTWATER_RECORDS'
export const   GET_ALL_GOAT_TRAUMA_RECORDS = 'GET_ALL_GOAT_TRAUMA_RECORDS'
export const   GET_ALL_GOAT_HEMONCHOSIS_RECORDS = 'GET_ALL_GOAT_HEMONCHOSIS_RECORDS'

//--------------------------END OF GOAT SECTION-------------------------------------//



//----------------------------QUAIL DISEASES--------------------------------//
export const GET_FILTERED_QUAIL_PM_START_TIME = 'GET_FILTERED_QUAIL_PM_START_TIME'
export const GET_FILTERED_QUAIL_PM_END_TIME = 'GET_FILTERED_QUAIL_PM_END_TIME'



export const   GET_ALL_QUAIL_COLIBACILLOSIS_RECORDS = 'GET_ALL_QUAIL_COLIBACILLOSIS_RECORDS'
export const   GET_ALL_QUAIL_SALMONELLOSIS_RECORDS = 'GET_ALL_QUAIL_SALMONELLOSIS_RECORDS'

//--------------------------END OF QUAIL SECTION-------------------------------------//


//----------------------------RABBIT DISEASES--------------------------------//
export const GET_FILTERED_RABBIT_PM_START_TIME = 'GET_FILTERED_RABBIT_PM_START_TIME'
export const GET_FILTERED_RABBIT_PM_END_TIME = 'GET_FILTERED_RABBIT_PM_END_TIME'



export const   GET_ALL_RABBIT_COCCIDIOSIS_RECORDS = 'GET_ALL_RABBIT_COCCIDIOSIS_RECORDS'
export const   GET_ALL_RABBIT_BACTERIAL_INFECTION_RECORDS = 'GET_ALL_RABBIT_BACTERIAL_INFECTION_RECORDS'

//--------------------------END OF QUAIL SECTION-------------------------------------//


//----------------------------CATTLE DISEASES--------------------------------//
export const GET_FILTERED_CATTLE_PM_START_TIME = 'GET_FILTERED_CATTLE_PM_START_TIME'
export const GET_FILTERED_CATTLE_PM_END_TIME = 'GET_FILTERED_CATTLE_PM_END_TIME'



export const   GET_ALL_CATTLE_ANAPLASMOSIS_RECORDS = 'GET_ALL_CATTLE_ANAPLASMOSIS_RECORDS'

//--------------------------END OF QUAIL SECTION-------------------------------------//


//--------------------------BEEF AI SECTION---------------------------------------------//
export const GET_FILTERED_BEEF_AI_START_TIME = 'GET_FILTERED_BEEF_AI_START_TIME'
export const GET_FILTERED_BEEF_AI_END_TIME = 'GET_FILTERED_BEEF_AI_END_TIME'


export const ADD_BEEF_AI_RECORD = 'ADD_BEEF_AI_RECORD'
export const   GET_ALL_BEEF_AI_RECORDS = 'GET_ALL_BEEF_AI_RECORDS'

export const   GET_ALL_BEEF_AI_SALES_RECORDS = 'GET_ALL_BEEF_AI_SALES_RECORDS'
export const   GET_ALL_BEEF_AI_CONSULTS_RECORDS = 'GET_ALL_BEEF_AI_CONSULTS_RECORDS'

//=========================END OF SECTION==============================================//


//--------------------------PIG AI SECTION---------------------------------------------//
export const GET_FILTERED_PIG_AI_START_TIME = 'GET_FILTERED_PIG_AI_START_TIME'
export const GET_FILTERED_PIG_AI_END_TIME = 'GET_FILTERED_PIG_AI_END_TIME'


export const ADD_PIG_AI_RECORD = 'ADD_PIG_AI_RECORD'
export const   GET_ALL_PIG_AI_RECORDS = 'GET_ALL_PIG_AI_RECORDS'
export const   GET_ALL_FILTERED_PIG_AI_RECORDS = 'GET_ALL_FILTERED_PIG_AI_RECORDS'

//==============================END OF SECTION========================================//


//--------------------------FENCE SECTION---------------------------------------------//
export const GET_FILTERED_FENCE_START_TIME = 'GET_FILTERED_FENCE_START_TIME'
export const GET_FILTERED_FENCE_END_TIME = 'GET_FILTERED_FENCE_END_TIME'


export const ADD_FENCE_RECORD = 'ADD_FENCE_RECORD'
export const   GET_ALL_FENCE_RECORDS = 'GET_ALL_FENCE_RECORDS'
export const   GET_ALL_FILTERED_FENCE_RECORDS = 'GET_ALL_FILTERED_FENCE_RECORDS'

//==============================END OF SECTION========================================//


//--------------------------FISH SECTION---------------------------------------------//
export const GET_FILTERED_FISH_START_TIME = 'GET_FILTERED_FISH_START_TIME'
export const GET_FILTERED_FISH_END_TIME = 'GET_FILTERED_FISH_END_TIME'


export const ADD_FISH_RECORD = 'ADD_FISH_RECORD'
export const   GET_ALL_FISH_RECORDS = 'GET_ALL_FISH_RECORDS'
export const   GET_ALL_FILTERED_FISH_RECORDS = 'GET_ALL_FILTERED_FISH_RECORDS'

//==============================END OF SECTION========================================//


//--------------------------IRRIGATION SECTION---------------------------------------------//
export const GET_FILTERED_IRRIGATION_START_TIME = 'GET_FILTERED_IRRIGATION_START_TIME'
export const GET_FILTERED_IRRIGATION_END_TIME = 'GET_FILTERED_IRRIGATION_END_TIME'


export const ADD_IRRIGATION_RECORD = 'ADD_IRRIGATION_RECORD'
export const   GET_ALL_IRRIGATION_RECORDS = 'GET_ALL_IRRIGATION_RECORDS'
export const   GET_ALL_FILTERED_IRRIGATION_RECORDS = 'GET_ALL_FILTERED_IRRIGATION_RECORDS'

//==============================END OF SECTION========================================//


//--------------------------WATER_PUMP SECTION---------------------------------------------//
export const GET_FILTERED_WATER_PUMP_START_TIME = 'GET_FILTERED_WATER_PUMP_START_TIME'
export const GET_FILTERED_WATER_PUMP_END_TIME = 'GET_FILTERED_WATER_PUMP_END_TIME'


export const   ADD_WATER_PUMP_RECORD = 'ADD_WATER_PUMP_RECORD'
export const   GET_ALL_WATER_PUMP_RECORDS = 'GET_ALL_WATER_PUMP_RECORDS'
export const   GET_ALL_FILTERED_WATER_PUMP_RECORDS = 'GET_ALL_FILTERED_WATER_PUMP_RECORDS'

//==============================END OF SECTION========================================//



//--------------------------WATER_PUMP SECTION---------------------------------------------//
export const GET_FILTERED_TOTAL_CONSULTS_START_TIME = 'GET_FILTERED_TOTAL_CONSULTS_START_TIME'
export const GET_FILTERED_TOTAL_CONSULTS_END_TIME = 'GET_FILTERED_TOTAL_CONSULTS_END_TIME'



export const   GET_ALL_TOTAL_CONSULTS_RECORDS = 'GET_ALL_TOTAL_CONSULTS_RECORDS'
export const   GET_ALL_FILTERED_TOTAL_CONSULTS_RECORDS = 'GET_ALL_FILTERED_TOTAL_CONSULTS_RECORDS'

export const GET_ALL_FILTERED_TOTAL_AGRO_RECORDS = 'GET_ALL_FILTERED_TOTAL_AGRO_RECORDS'
export const GET_ALL_FILTERED_TOTAL_BEEF_AI_RECORDS = 'GET_ALL_FILTERED_TOTAL_BEEF_AI_RECORDS'
export const GET_ALL_FILTERED_TOTAL_FENCE_RECORDS = 'GET_ALL_FILTERED_TOTAL_FENCE_RECORDS'
export const GET_ALL_FILTERED_TOTAL_FISH_RECORDS = 'GET_ALL_FILTERED_TOTAL_FISH_RECORDS'
export const GET_ALL_FILTERED_TOTAL_IRRIGATION_RECORDS = 'GET_ALL_FILTERED_TOTAL_IRRIGATION_RECORDS'
export const GET_ALL_FILTERED_TOTAL_NUTRITION_RECORDS = 'GET_ALL_FILTERED_TOTAL_NUTRITION_RECORDS'
export const GET_ALL_FILTERED_TOTAL_PIG_AI_RECORDS = 'GET_ALL_FILTERED_TOTAL_PIG_AI_RECORDS'
export const GET_ALL_FILTERED_TOTAL_PUMP_RECORDS = 'GET_ALL_FILTERED_TOTAL_PUMP_RECORDS'
export const GET_ALL_FILTERED_TOTAL_VET_RECORDS = 'GET_ALL_FILTERED_TOTAL_VET_RECORDS'
export const GET_ALL_FILTERED_TOTAL_POST_MORTEMS_RECORDS = 'GET_ALL_FILTERED_TOTAL_POST_MORTEMS_RECORDS'

//==============================END OF SECTION========================================//


//------------------------------LAB SECTION -----------------------------------------//

export const ADD_SAMPLE_INFORMATION_RECORD = 'ADD_SAMPLE_INFORMATION_RECORD'
export const GET_ALL_SAMPLE_INFORMATION_RECORDS = 'GET_ALL_SAMPLE_INFORMATION_RECORDS'
export const GET_ALL_FILTERED_SAMPLE_INFORMATION_RECORDS = 'GET_ALL_FILTERED_SAMPLE_INFORMATION_RECORDS'

export const GET_FILTERED_SAMPLE_INFORMATION_START_TIME = 'GET_FILTERED_SAMPLE_INFORMATION_START_TIME'
export const GET_FILTERED_SAMPLE_INFORMATION_END_TIME = 'GET_FILTERED_SAMPLE_INFORMATION_END_TIME'



export const ADD_SUBMISSIONS_RECORD = 'ADD_SUBMISSIONS_RECORD'
export const GET_ALL_SUBMISSIONS_RECORDS = 'GET_ALL_SUBMISSIONS_RECORDS'
export const GET_ALL_FILTERED_SUBMISSIONS_RECORDS = 'GET_ALL_FILTERED_SUBMISSIONS_RECORDS'

export const GET_FILTERED_SUBMISSIONS_START_TIME = 'GET_FILTERED_SUBMISSIONS_START_TIME'
export const GET_FILTERED_SUBMISSIONS_END_TIME = 'GET_FILTERED_SUBMISSIONS_END_TIME'

